---
# tasks file for while_true_do.srv_docker

- name: Include distribution Tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Manage docker Packages
  package:
    name: "{{ wtd_srv_docker_packages }}"
    state: "{{ wtd_srv_docker_packages_state }}"
  become: yes
  tags:
    - docker
    - package

- name: Manage docker Service
  service:
    name: "{{ wtd_srv_docker_service }}"
    state: "{{ wtd_srv_docker_service_state }}"
    enabled: "{{ wtd_srv_docker_service_enabled }}"
  become: yes
  when:
    - ansible_virtualization_type != "docker"
    - wtd_srv_docker_packages_state != "absent"
  tags:
    - docker
    - service

- name: Manage docker Group
  group:
    name: "{{ wtd_srv_docker_group }}"
    state: "{{ wtd_srv_docker_group_state }}"
  become: yes
  when: wtd_srv_docker_packages_state != "absent"
  tags:
    - docker
    - group

- name: Manage docker Group Users
  user:
    name: "{{ item }}"
    groups: "{{ wtd_srv_docker_group }}"
    append: yes
  become: yes
  loop: "{{ wtd_srv_docker_group_users }}"
  when:
    - wtd_srv_docker_group_state == "present"
    - wtd_srv_docker_packages_state != "absent"
  tags:
    - docker
    - group
    - user
