---
# tasks file for while_true_do.srv_docker

- name: Include docker package Tasks
  include_tasks: "docker_{{ wtd_srv_docker_package_source }}.yml"
  tags:
    - docker
    - container
    - package
    - repository

- name: Include docker-compose Tasks
  include_tasks: "docker_compose.yml"
  when:
    - wtd_srv_docker_compose_package_state != "unmanaged"
  tags:
    - docker
    - container
    - development
    - package

- name: Manage docker Group
  group:
    name: "{{ wtd_srv_docker_group }}"
    state: "{{ wtd_srv_docker_group_state }}"
  become: true
  when:
    - wtd_srv_docker_package_state != "absent"
  tags:
    - docker
    - container
    - group
    - user

- name: Manage docker Service
  service:
    name: "{{ wtd_srv_docker_service }}"
    state: "{{ wtd_srv_docker_service_state }}"
    enabled: "{{ wtd_srv_docker_service_enabled }}"
  become: true
  when:
    - wtd_srv_docker_package_state != "absent"
    - ansible_virtualization_type != "docker"
  tags:
    - docker
    - container
    - service

- name: Manage docker Users
  user:
    name: "{{ item }}"
    groups: "{{ wtd_srv_docker_group }}"
    append: true
  become: true
  loop: "{{ wtd_srv_docker_group_users }}"
  when:
    - wtd_srv_docker_group_state == "present"
    - wtd_srv_docker_package_state != "absent"
  tags:
    - docker
    - container
    - group
    - user
